### ISSUE TITLE
Unclear dataformat specification

### ISSUE THREAD

**Issue by ivozandhuis** [CLARIAH/burgerLinker#6]
First of all: thank you very, very much for building this tool. It is very cool!

I created a ttl-file with two events: birth and marriage. I expect the newborn of the birth to be linked (owl:sameAs) to the groom of the marriage.

After creating the HDT file, I ran the ShowDatasetStats function. 1 Birth event, 1 Marriage event and 9 Individuals were detected. So far so good, except that I had to use http:// for schema:Person and introduce https:// for sdo:givenName. If I don't, the individuals are not detected. Apparently, http://schema.org/Person is needed for the class and httpS://schema.org/givenName for the property. (Although they're both defined as http:// in the ontology)

Next step: using the Within_B_M function. All numbers in the output are 0, as if it didn't detect the events anymore. I guess I am doing something wrong in the data format, but I am not able to figure out what. Does the Within_B_M function use yet other http/https namespaces for schema.org?

``` ttl
@prefix bio: <http://purl.org/vocab/bio/0.1/> .
@prefix civ: <https://iisg.amsterdam/id/civ/> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix schema: <http://schema.org/> .
@prefix sdo: <https://schema.org/> .
@prefix xml: <http://www.w3.org/XML/1998/namespace> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<https://www.openarch.nl/brd:290ad17f-d2aa-0a0b-1417-799cd4717252#Huwelijk> a civ:Marriage ;
    civ:bride <https://www.openarch.nl/brd:290ad17f-d2aa-0a0b-1417-799cd4717252#Person:fb79612d-e987-ce08-c88a-32246967595e> ;
    civ:eventDate "1854-05-08"^^xsd:date ;
    civ:eventLocation "Breda" ;
    civ:fatherBride <https://www.openarch.nl/brd:290ad17f-d2aa-0a0b-1417-799cd4717252#Person:4257e262-c612-7516-3248-3e4c21575739> ;
    civ:fatherGroom <https://www.openarch.nl/brd:290ad17f-d2aa-0a0b-1417-799cd4717252#Person:f60fa958-fa42-c6c7-2fdd-83f9e095aadb> ;
    civ:groom <https://www.openarch.nl/brd:290ad17f-d2aa-0a0b-1417-799cd4717252#Person:dfa7c411-0868-5a33-e4f4-da1775d06706> ;
    civ:motherBride <https://www.openarch.nl/brd:290ad17f-d2aa-0a0b-1417-799cd4717252#Person:3e3b0c46-3039-7b13-5300-491fc0bb6540> ;
    civ:motherGroom <https://www.openarch.nl/brd:290ad17f-d2aa-0a0b-1417-799cd4717252#Person:81420772-0fbc-2696-8d9d-3baf258fc948> .

<https://www.openarch.nl/wba:abf44138-f8d9-11df-a690-cd95c1e286e2#Geboorte> a civ:Birth ;
    civ:eventDate "1827-04-13"^^xsd:date ;
    civ:eventLocation "Hoeven" ;
    civ:father <https://www.openarch.nl/wba:abf44138-f8d9-11df-a690-cd95c1e286e2#Person:557b5ee0-f8de-11df-a690-cd95c1e286e2> ;
    civ:mother <https://www.openarch.nl/wba:abf44138-f8d9-11df-a690-cd95c1e286e2#Person:557b9392-f8de-11df-a690-cd95c1e286e2> ;
    civ:newborn <https://www.openarch.nl/wba:abf44138-f8d9-11df-a690-cd95c1e286e2#Person:557b2ba0-f8de-11df-a690-cd95c1e286e2> .

<https://www.openarch.nl/brd:290ad17f-d2aa-0a0b-1417-799cd4717252#Person:3e3b0c46-3039-7b13-5300-491fc0bb6540> a schema:Person ;
    civ:personID "Person:3e3b0c46-3039-7b13-5300-491fc0bb6540" ;
    sdo:familyName "Leest" ;
    sdo:givenName "Adriana" .

<https://www.openarch.nl/brd:290ad17f-d2aa-0a0b-1417-799cd4717252#Person:4257e262-c612-7516-3248-3e4c21575739> a schema:Person ;
    civ:personID "Person:4257e262-c612-7516-3248-3e4c21575739" ;
    civ:prefixFamilyName "van der" ;
    sdo:familyName "Jagt" ;
    sdo:givenName "Abraham" .

<https://www.openarch.nl/brd:290ad17f-d2aa-0a0b-1417-799cd4717252#Person:81420772-0fbc-2696-8d9d-3baf258fc948> a schema:Person ;
    civ:personID "Person:81420772-0fbc-2696-8d9d-3baf258fc948" ;
    sdo:familyName "Kerstens" ;
    sdo:givenName "Cornelia" .

<https://www.openarch.nl/brd:290ad17f-d2aa-0a0b-1417-799cd4717252#Person:dfa7c411-0868-5a33-e4f4-da1775d06706> a schema:Person ;
    civ:personID "Person:dfa7c411-0868-5a33-e4f4-da1775d06706" ;
    civ:prefixFamilyName "van" ;
    sdo:familyName "Aken" ;
    sdo:givenName "Willem" .

<https://www.openarch.nl/brd:290ad17f-d2aa-0a0b-1417-799cd4717252#Person:f60fa958-fa42-c6c7-2fdd-83f9e095aadb> a schema:Person ;
    civ:personID "Person:f60fa958-fa42-c6c7-2fdd-83f9e095aadb" ;
    civ:prefixFamilyName "van" ;
    sdo:familyName "Aken" ;
    sdo:givenName "Adriaan" .

<https://www.openarch.nl/brd:290ad17f-d2aa-0a0b-1417-799cd4717252#Person:fb79612d-e987-ce08-c88a-32246967595e> a schema:Person ;
    civ:personID "Person:fb79612d-e987-ce08-c88a-32246967595e" ;
    civ:prefixFamilyName "van der" ;
    sdo:familyName "Jagt" ;
    sdo:givenName "Alida Cornelia" .

<https://www.openarch.nl/wba:abf44138-f8d9-11df-a690-cd95c1e286e2#Person:557b2ba0-f8de-11df-a690-cd95c1e286e2> a schema:Person ;
    civ:personID "Person:557b2ba0-f8de-11df-a690-cd95c1e286e2" ;
    civ:prefixFamilyName "van" ;
    sdo:familyName "Aken" ;
    sdo:givenName "Willem" .

<https://www.openarch.nl/wba:abf44138-f8d9-11df-a690-cd95c1e286e2#Person:557b5ee0-f8de-11df-a690-cd95c1e286e2> a schema:Person ;
    civ:personID "Person:557b5ee0-f8de-11df-a690-cd95c1e286e2" ;
    civ:prefixFamilyName "van" ;
    sdo:familyName "Aken" ;
    sdo:givenName "Adriaan" .

<https://www.openarch.nl/wba:abf44138-f8d9-11df-a690-cd95c1e286e2#Person:557b9392-f8de-11df-a690-cd95c1e286e2> a schema:Person ;
    civ:personID "Person:557b9392-f8de-11df-a690-cd95c1e286e2" ;
    sdo:familyName "Kerstens" ;
    sdo:givenName "Cornelia" .
```

**Comment by raadjoe** [comment]
Hi Ivo, many thanks for your helpful comments. 
There has been a stupid mistake from my side: I forgot to upload the latest JAR file that is compatible with the new data model (which we slightly changed 9 days ago). 
This must have been very frustrating for you using the old release with an incompatible data model, sorry for that.

I now uploaded a new release ([v 0.2)](https://github.com/CLARIAH/burgerLinker/releases/tag/v0.2) of burgerLinker, that contains also additional linking functionalities. 
Please let me know if any issue remains in the new version.

**Comment by ivozandhuis** [comment]
Thanks! No problem: part of the job of innovation :-)
Nice new features! I'm still not able to get it working though. I suspect issue #5 has something to do with it. Does the example above work for you?

**Comment by raadjoe** [comment]
I updated now the jar file in the same release ([v 0.2)](https://github.com/CLARIAH/burgerLinker/releases/tag/v0.2).
In this update, I added support for both http://schema.org and https://schema.org.

The tool works correctly on the example file that you provided, but there's still one remaining issue in your file, which is the absence of the `civ:registrationID` statement that is used for saving the links (see [Wiki](https://github.com/CLARIAH/burgerLinker/wiki/Adapting-the-data-model)). Any unique value for `civ:registrationID` would work (not necessarily an integer).

P.S. There are still some issues that I need to fix in saving the detected links as RDF with their metadata (as named graphs), so I suggest for now to keep the output format as CSV (i.e. not changing the [--format](https://github.com/CLARIAH/burgerLinker#tool-parameters) default's value, by simply not adding this parameter when running burgerLinker).

**Comment by ivozandhuis** [comment]
Thank you! I got it to work this time.

You might add a link to the wiki on the README page.

**Comment by raadjoe** [comment]
Great! I now [added a link](https://github.com/CLARIAH/burgerLinker/commit/dc229b66030013d23f1539eecb7ab106e3e9c231) to the Wiki on the README page.
