### ISSUE TITLE
credits to data

### ISSUE THREAD

**Issue by rlzijdeman** [CLARIAH/burgerLinker#9]
﻿﻿Q: if a researcher uses this beautiful tool, how would he/she give credit to the tool and the data which comes with it? (by Andrea Scharnhorst)

**Comment by rijpma** [comment]
Tool: would http://ceur-ws.org/Vol-2695/paper6.pdf work?

Data: I think it'd be nice if there was some reference that included everyone's contributions including the archives and volunteers, like on https://wiki.openstreetmap.org/wiki/Researcher_Information#Citation_requirements

**Comment by rlzijdeman** [comment]
ps: the data idea will be adopted by HSNDB, which provides the LINKS data.
